server:
  port: 8084
  servlet:
    context-path: /

spring:
  profiles:
    active: ${ENV:dev}
  application:
    name: ts-bi-service
  banner:
    location: classpath:banner.txt
  dubbo:
    server: true
    application:
      name: bi-consumer-service
      id: ${spring.dubbo.application.name}

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

