debug: true
trace: false

spring:
  profiles: local
  datasource:
      url: jdbc:mysql://172.20.30.110:8066/${MYSQL_DB:rent_platform}?autoReconnect=true
      username: ${MYSQL_USER:rent_platform}
      password: ${MYSQL_PASSWORD:rent_platform}
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
  dubbo:
    registry:
      address: zookeeper://zk01.dev:2181
    protocol: dubbo

logging:
  level:
    org.apache.ibatis: debug
    springframework.web: debug
    org.springboot.sample: debug

# biguava组件配置
biguava:
  enabled: false
  level: height
  monitorTime: 121
  hello:
    keys: 1234asdf
    desc: i am biguava sample

